### ISSUE TITLE
Campo de Programa Educativo depende Dependencia

### ISSUE THREAD

**Issue by lfmarin** [UVRoboticsLab-boca/SisCoRED20#10]
PROGRAMA | X | V | C/O | PR/T | C/M 
 -- | -- | -- | -- | -- | --
Ingeniería Petrolera |   |   |   | X | X
Ciencias Atmosféricas | X |   |   |   |  
Ingeniería Ambiental | X |   | X | X | X
Ingeniería Civil | X | X | X | X | X
Ingeniería en Biotecnología |   |   | X |   | X
Ingeniería en Electrónica y Comunicaciones |   | X |   | X |  
Ingeniería en Instrumentación Electrónica | X |   |   |   |  
Ingeniería  Metalúrgica y Ciencia de los Materiales |   | X |   |   |  
Ingeniería Naval |   | X |   |   |  
Ingeniería Química | X | X | X | X | X
Ingeniería Topográfica Geodésica |   | X |   |   |  
Matemáticas | X |   |   |   |  
Ingeniería Mecánica Eléctrica | X | X | X | X | X
Ingeniería en Alimentos | X |   | X |   |  
Ingeniería en Tecnologías Computacionales |   |   |   | X |  
Ingeniería Industrial |   | X | X | X |  
Ingeniería Informática |   | X |   |   |  
Ingeniería Mecatrónica |   | X | X |   |  
Química Industrial |   |   | X |   |  
Químico Farmacéutico Biólogo | X |   | X |   |  
Arquitectura | X | X | X | X |  
Ingeniería Biomédica | X |   |   |   |

**Comment by lfmarin** [comment]
Corrección  debe quedar por dependencia según el siguiente archivo:

[PEs DGAAT.docx](https://github.com/UVRoboticsLab-boca/SisCoRED20/files/4136008/PEs.DGAAT.docx)

**Comment by RobertoGarciaMtz** [comment]
Se resolvio el filtrado de dependencias
