### ISSUE TITLE
Campos check box

### ISSUE THREAD

**Issue by RobertoGarciaMtz** [UVRoboticsLab-boca/SisCoRED20#3]
Algunos campos dentro de estrategias metodologicas no se encuentran definidos, por lo que al momento de guardar se muestran de la siguiente manera

[Ejemplo_undefined.docx](https://github.com/UVRoboticsLab-boca/SisCoRED20/files/4125680/Ejemplo_undefined.docx)

**Comment by lfmarin** [comment]
@RobertoGarciaMtz  definir cuales son los campos que marca como undefined

**Comment by RobertoGarciaMtz** [comment]
Se relacionaron los Campos de checkbox
de manera adecuada
